Settings
witseie-elen4010/2022-group-lab-005 pull request #72
Opened 2022-06-03 20:50 UTC by RobynGebbie

Settings page is now compatible with database changes and uses a stylesheet

2022-06-04 07:44 UTC, UntidyRAM commented on src/public/fetchMode.js
>    .then(function (data) {
Please put this on the same line as the fetch statement on line 4 :)

2022-06-04 07:45 UTC, UntidyRAM commented on src/public/fetchMode.js
>    .catch(error => document.write(`Fetch failed: ${error}`))
Please put this on the line above.

2022-06-04 07:46 UTC, UntidyRAM commented on src/public/fetchMode.js
>  fetch('/user/api/DarkModeData')
Please move line 6 to the end of this line :)

2022-06-04 08:17 UTC, UntidyRAM requested changes
There seems to be a bit of a weird bug. When I go to the settings page (from the main page), I click the dark mode button and it makes the page dark (which is correct). Now I stay on the settings page and click the light mode button which makes the page light (which is still correct). But when I click the dark mode button again, the page does not go dark. Also, if I keep clicking the dark mode button, the page toggles between light and dark (this is also true for the light mode button).

I also seem to get this error ```Fetch failed: TypeError: NetworkError when attempting to fetch resource.``` Not sure what's making it happen. My hunch is that the code isn't using Promises so the client/server aren't waiting for the DB query to finish.

2022-06-04 08:17 UTC, UntidyRAM commented on src/services/settings_db.cjs
> +    const sqlCode = `UPDATE [dbo].[UserSettings] SET DarkMode = '${DarkMode}' WHERE ID = '1'`
Please make sure you sanitize this variable before sending this query to the DB. If someone modifies your session storage variable so that it contains SQL code (take a look at [this](https://www.w3schools.com/sql/sql_injection.asp)).

2022-06-04 08:17 UTC, UntidyRAM commented on src/services/settings_db.cjs
> +    const mode = await pool.request().query("SELECT DarkMode FROM [dbo].[UserSettings] WHERE ID = '1'")
Is the ```WHERE ID = '1'``` just for debugging?

2022-06-05 11:11 UTC, RobynGebbie commented on src/public/settings.cjs
>    sendModeToServer(mode)
No, because I want to reuse this file on all other pages but only this function will be needed

2022-06-05 11:12 UTC, RobynGebbie commented on src/services/settings_db.cjs
> +    const mode = await pool.request().query("SELECT DarkMode FROM [dbo].[UserSettings] WHERE ID = '1'")
Yes

2022-06-05 14:15 UTC, RobynGebbie commented on src/services/settings_db.cjs
> +  changeMode: async function changeMode (DarkMode) {
I took a look and you are returning text and not a promise just as I was :). I even fetched from your query and it returned text, you are not returning a promise at all :)

2022-06-05 14:18 UTC, closed without merging